[package]
name = "blitz"
description = "High-level APIs for rendering HTML with Blitz"
version = "0.1.0-alpha.1"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/blitz"
license.workspace = true
edition = "2024"

[features]
default = ["net", "accessibility", "menu", "tracing"]
net = ["dep:tokio", "dep:url", "dep:blitz-net"]
accessibility = ["blitz-shell/accessibility"]
menu = ["blitz-shell/menu"]
tracing = ["blitz-shell/tracing"]
svg = ["blitz-renderer-vello/svg"]

[dependencies]
# Blitz dependencies
anyrender_vello = { path = "../anyrender_vello" }
blitz-html = { version = "0.1.0-alpha.1", path = "../blitz-html" }
blitz-shell = { version = "0.1.0-alpha.1", path = "../blitz-shell" }
blitz-net = { version = "0.1.0-alpha.1", path = "../blitz-net", optional = true }
blitz-traits = { version = "0.1.0-alpha.1", path = "../blitz-traits" }
blitz-renderer-vello = { path = "../blitz-renderer-vello" }

# IO & Networking
url = { workspace = true, features = ["serde"], optional = true }
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
