// <auto-generated>Helper for accessing embedded resources.</auto-generated>
using System;
using System.IO;
using System.Reflection;
using System.Text;

namespace BlitzWinRTTestApp
{
    internal static class EmbeddedContent
    {
        private static string? _demoHtml;
        private const string DemoHtmlResourceName = "BlitzWinRTTestApp.Assets.demo.html";

        public static string DemoHtml => _demoHtml ??= ReadResource(DemoHtmlResourceName);

        private static string ReadResource(string name)
        {
            var asm = Assembly.GetExecutingAssembly();
            using var stream = asm.GetManifestResourceStream(name) ?? throw new InvalidOperationException($"Embedded resource '{name}' not found. Check LogicalName in csproj.");
            using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: 8192, leaveOpen: false);
            return reader.ReadToEnd();
        }
    }
}
