[package]
name = "anyrender_d2d"
version = "0.5.0"
edition = "2024"
license.workspace = true
repository = "https://github.com/dioxuslabs/blitz"
description = "Direct2D backend for anyrender"

[dependencies]
anyrender = { workspace = true }
rustc-hash = { workspace = true }
windows = { version = "0.58", features = [
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_DirectWrite",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_WindowsProgramming",
    "Win32_System_Diagnostics",
    "Win32_System_Diagnostics_Debug",
    "Foundation",
    "Foundation_Numerics"
] }
kurbo = { workspace = true }
peniko = { workspace = true }
blitz-metrics = { workspace = true }
