[package]
name = "blitz-renderer-vello"
version = "0.1.0"
license.workspace = true
edition = "2021"

[features]
default = ["tracing", "svg"]
tracing = ["dep:tracing"]
svg = ["dep:vello_svg", "blitz-dom/svg"]

[dependencies]
blitz-traits = { path = "../blitz-traits" }
blitz-dom = { path = "../blitz-dom", default-features = false }
style = { workspace = true, features = ["servo"] }
euclid = { workspace = true }
taffy = { workspace = true }
parley = { workspace = true }
tracing = { workspace = true, optional = true }
color = { workspace = true }
vello = { workspace = true }
vello_svg = { workspace = true, optional = true }
wgpu = { workspace = true }
raw-window-handle = { workspace = true }
image = { workspace = true }
futures-intrusive = { workspace = true }
pollster = { workspace = true }
windows-numerics = "0.1.1"

[dependencies.windows]
version = "0.60.0"
features = [
    "Win32_System_Com",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_DirectWrite",
    "Win32_System_LibraryLoader",
    "Win32_System_Performance",
    "Win32_System_SystemInformation",
    "Win32_UI_Animation",
    "Win32_UI_WindowsAndMessaging",
]