[package]
name = "blitz-winrt"
version = "0.1.0"
license = "MIT OR Apache-2.0 OR MPL-2.0"
description = "Blitz WinRT"
keywords = ["blitz", "winrt"]
categories = ["gui"]
edition = "2021"
repository = ""

[lib]
crate-type = ["cdylib"]

[dependencies]
# Core Blitz dependencies
blitz-dom = { workspace = true, features = ["default"] }
blitz-traits = { workspace = true }
blitz-html = { workspace = true }

# Rendering dependencies
anyrender = { workspace = true }
anyrender_vello = { workspace = true }
wgpu = { workspace = true }
vello = { workspace = true }

# Async runtime
tokio = { workspace = true, features = ["macros", "rt", "sync"] }

# Windows-specific dependencies
comrak = { version = "0.40.0", default-features = false }
keyboard-types = { workspace = true }
scopeguard = "1.2"
windows.workspace = true
windows-core.workspace = true
windows-targets.workspace = true
windows-numerics.workspace = true

# Utility dependencies
rustc-hash = { workspace = true }
bytes = { workspace = true }
tracing = { workspace = true }
smol_str = { workspace = true }

[build-dependencies]
windows-bindgen.workspace=true
windows-metadata.workspace=true
