// Bindings generated by `windows-bindgen` 0.62.1

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Host(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(Host, windows_core::IUnknown, windows_core::IInspectable);
impl Host {
    pub fn SetPanel<P0>(&self, attacher: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<windows_core::IInspectable>,
    {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetPanel)(
                windows_core::Interface::as_raw(this),
                attacher.param().abi(),
            )
            .ok()
        }
    }
    pub fn Resize(&self, width: u32, height: u32, scale: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).Resize)(
                windows_core::Interface::as_raw(this),
                width,
                height,
                scale,
            )
            .ok()
        }
    }
    pub fn RenderOnce(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RenderOnce)(windows_core::Interface::as_raw(
                this,
            ))
            .ok()
        }
    }
    pub fn LoadHtml(&self, html: &windows_core::HSTRING) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).LoadHtml)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(html),
            )
            .ok()
        }
    }
    pub fn SetVerboseLogging(&self, enabled: bool) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetVerboseLogging)(
                windows_core::Interface::as_raw(this),
                enabled,
            )
            .ok()
        }
    }
    pub fn TestAttacherConnection(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TestAttacherConnection)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn CreateInstance<P0>(
        attacher: P0,
        width: u32,
        height: u32,
        scale: f32,
    ) -> windows_core::Result<Host>
    where
        P0: windows_core::Param<windows_core::IInspectable>,
    {
        Self::IHostFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                attacher.param().abi(),
                width,
                height,
                scale,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IHostFactory<R, F: FnOnce(&IHostFactory) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<Host, IHostFactory> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for Host {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IHost>();
}
unsafe impl windows_core::Interface for Host {
    type Vtable = <IHost as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IHost as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for Host {
    const NAME: &'static str = "BlitzWinUI.Host";
}
unsafe impl Send for Host {}
unsafe impl Sync for Host {}
windows_core::imp::define_interface!(IHost, IHost_Vtbl, 0xe152c88b_c991_5a71_8c7f_11d89dd8512a);
impl windows_core::RuntimeType for IHost {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IHost {
    const NAME: &'static str = "BlitzWinUI.IHost";
}
pub trait IHost_Impl: windows_core::IUnknownImpl {
    fn SetPanel(
        &self,
        attacher: windows_core::Ref<'_, windows_core::IInspectable>,
    ) -> windows_core::Result<()>;
    fn Resize(&self, width: u32, height: u32, scale: f32) -> windows_core::Result<()>;
    fn RenderOnce(&self) -> windows_core::Result<()>;
    fn LoadHtml(&self, html: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn SetVerboseLogging(&self, enabled: bool) -> windows_core::Result<()>;
    fn TestAttacherConnection(&self) -> windows_core::Result<bool>;
}
impl IHost_Vtbl {
    pub const fn new<Identity: IHost_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn SetPanel<Identity: IHost_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            attacher: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IHost_Impl::SetPanel(this, core::mem::transmute_copy(&attacher)).into()
            }
        }
        unsafe extern "system" fn Resize<Identity: IHost_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            width: u32,
            height: u32,
            scale: f32,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IHost_Impl::Resize(this, width, height, scale).into()
            }
        }
        unsafe extern "system" fn RenderOnce<Identity: IHost_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IHost_Impl::RenderOnce(this).into()
            }
        }
        unsafe extern "system" fn LoadHtml<Identity: IHost_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            html: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IHost_Impl::LoadHtml(this, core::mem::transmute(&html)).into()
            }
        }
        unsafe extern "system" fn SetVerboseLogging<Identity: IHost_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            enabled: bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IHost_Impl::SetVerboseLogging(this, enabled).into()
            }
        }
        unsafe extern "system" fn TestAttacherConnection<
            Identity: IHost_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IHost_Impl::TestAttacherConnection(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IHost, OFFSET>(),
            SetPanel: SetPanel::<Identity, OFFSET>,
            Resize: Resize::<Identity, OFFSET>,
            RenderOnce: RenderOnce::<Identity, OFFSET>,
            LoadHtml: LoadHtml::<Identity, OFFSET>,
            SetVerboseLogging: SetVerboseLogging::<Identity, OFFSET>,
            TestAttacherConnection: TestAttacherConnection::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IHost as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IHost_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SetPanel: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub Resize:
        unsafe extern "system" fn(*mut core::ffi::c_void, u32, u32, f32) -> windows_core::HRESULT,
    pub RenderOnce: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub LoadHtml: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetVerboseLogging:
        unsafe extern "system" fn(*mut core::ffi::c_void, bool) -> windows_core::HRESULT,
    pub TestAttacherConnection:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IHostFactory,
    IHostFactory_Vtbl,
    0x858fc9c7_4631_527b_bbee_315bebb62b45
);
impl windows_core::RuntimeType for IHostFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IHostFactory {
    const NAME: &'static str = "BlitzWinUI.IHostFactory";
}
pub trait IHostFactory_Impl: windows_core::IUnknownImpl {
    fn CreateInstance(
        &self,
        attacher: windows_core::Ref<'_, windows_core::IInspectable>,
        width: u32,
        height: u32,
        scale: f32,
    ) -> windows_core::Result<Host>;
}
impl IHostFactory_Vtbl {
    pub const fn new<Identity: IHostFactory_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn CreateInstance<
            Identity: IHostFactory_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            attacher: *mut core::ffi::c_void,
            width: u32,
            height: u32,
            scale: f32,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IHostFactory_Impl::CreateInstance(
                    this,
                    core::mem::transmute_copy(&attacher),
                    width,
                    height,
                    scale,
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IHostFactory, OFFSET>(),
            CreateInstance: CreateInstance::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IHostFactory as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IHostFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        u32,
        u32,
        f32,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ISwapChainAttacher,
    ISwapChainAttacher_Vtbl,
    0x36f88d95_0e3c_4e2a_a276_8a7a3b138b91
);
impl windows_core::RuntimeType for ISwapChainAttacher {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    ISwapChainAttacher,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl ISwapChainAttacher {
    pub fn AttachSwapChain(&self, swapchainptr: u64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).AttachSwapChain)(
                windows_core::Interface::as_raw(this),
                swapchainptr,
            )
            .ok()
        }
    }
    pub fn TestAttacherConnection(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TestAttacherConnection)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeName for ISwapChainAttacher {
    const NAME: &'static str = "BlitzWinUI.ISwapChainAttacher";
}
pub trait ISwapChainAttacher_Impl: windows_core::IUnknownImpl {
    fn AttachSwapChain(&self, swapchainPtr: u64) -> windows_core::Result<()>;
    fn TestAttacherConnection(&self) -> windows_core::Result<bool>;
}
impl ISwapChainAttacher_Vtbl {
    pub const fn new<Identity: ISwapChainAttacher_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn AttachSwapChain<
            Identity: ISwapChainAttacher_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            swapchainptr: u64,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ISwapChainAttacher_Impl::AttachSwapChain(this, swapchainptr).into()
            }
        }
        unsafe extern "system" fn TestAttacherConnection<
            Identity: ISwapChainAttacher_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISwapChainAttacher_Impl::TestAttacherConnection(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, ISwapChainAttacher, OFFSET>(),
            AttachSwapChain: AttachSwapChain::<Identity, OFFSET>,
            TestAttacherConnection: TestAttacherConnection::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<ISwapChainAttacher as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ISwapChainAttacher_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub AttachSwapChain:
        unsafe extern "system" fn(*mut core::ffi::c_void, u64) -> windows_core::HRESULT,
    pub TestAttacherConnection:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
}
